version: '2'

services:
  db:
    environment:
      MYSQL_DATABASE: 'car'
      MYSQL_ROOT_PASSWORD: 'root'
    image: mysql:8
    ports:
      - '3307:3306'
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local