spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3307/car?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3307/car?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    user: root
    password: root
  cache:
    type: redis
    redis:
      time-to-live: 10
  data:
    redis:
      host: localhost
      port: 6379

flyway:
  user: root
  password: root
  schemas: cars
